######################################################################
# Automatically generated by qmake (2.01a) pt. lut 18 22:36:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += application.h
SOURCES += application.cpp main.cpp
